engines:
  phpmd:
    enabled: true
    config: 
      file_extensions: "php"
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
ratings:
  paths:
    - "**.php"
    - "**.css"
exclude_paths:
- "semantic/dist/"
- "vendor/"
